package Vistas;

import clases.Jugador1;
import clases.Jugador2;
import clases.Jugador3;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/* Autor: Andres Felipe Martinez Orozco */

public class Tragamonedas extends javax.swing.JFrame {
    
    Jugador1 p1;
    Jugador2 p2;
    Jugador3 p3;
    
    boolean respuesta1 = false;
    boolean respuesta2 = false;
    boolean respuesta3 = false;

    public Tragamonedas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("TRAGA MONEDAS");
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB1 = new javax.swing.JLabel();
        lb1Persona1 = new javax.swing.JLabel();
        lb2Persona2 = new javax.swing.JLabel();
        lb3Persona3 = new javax.swing.JLabel();
        LB2 = new javax.swing.JButton();
        LB3 = new javax.swing.JButton();
        LB4 = new javax.swing.JButton();
        lb5 = new javax.swing.JButton();
        lb6 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LB1.setBackground(new java.awt.Color(102, 102, 255));
        LB1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LB1.setText("TRAGAMONEDAS FUTBOLISTAS");

        lb1Persona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N

        lb2Persona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N

        lb3Persona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N

        LB2.setBackground(new java.awt.Color(51, 255, 255));
        LB2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        LB2.setText("DETENER");
        LB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LB2ActionPerformed(evt);
            }
        });

        LB3.setBackground(new java.awt.Color(0, 255, 255));
        LB3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        LB3.setText("DETENER");
        LB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LB3ActionPerformed(evt);
            }
        });

        LB4.setBackground(new java.awt.Color(0, 255, 255));
        LB4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        LB4.setText("DETENER");
        LB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LB4ActionPerformed(evt);
            }
        });

        lb5.setBackground(new java.awt.Color(255, 255, 0));
        lb5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lb5.setText("INICIAR");
        lb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb5ActionPerformed(evt);
            }
        });

        lb6.setBackground(new java.awt.Color(255, 51, 51));
        lb6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lb6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Difícil ", "Fácil", "Normal" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB2)
                    .addComponent(lb1Persona1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB3)
                    .addComponent(lb2Persona2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LB4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb3Persona3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb5))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(LB1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb5)
                        .addGap(30, 30, 30)
                        .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb1Persona1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb2Persona2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb3Persona3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB2)
                    .addComponent(LB3)
                    .addComponent(LB4))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb5ActionPerformed
        // TODO add your handling code here:
        
        int tiempoMilisegundos = 0;
        switch (lb6.getSelectedIndex()) {
            case 0:
                tiempoMilisegundos = 0;
                break;
            case 1:
                tiempoMilisegundos = 500;
                break;
            case 2:
                tiempoMilisegundos = 100;
                break;
            default:
                tiempoMilisegundos = 0;
        }
        p1 = new Jugador1(tiempoMilisegundos, lb1Persona1);
        p2 = new Jugador2(tiempoMilisegundos, lb2Persona2);
        p3 = new Jugador3(tiempoMilisegundos, lb3Persona3);
        
        
        respuesta1 = false;
        respuesta2 = false;
        respuesta3 = false;
        lb5.setEnabled(false);
        p1.start();
        p2.start();
        p3.start();
    }//GEN-LAST:event_lb5ActionPerformed

    private void LB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LB2ActionPerformed
        p1.paro();
        respuesta1 = true;
        comprobarResultado();
    }//GEN-LAST:event_LB2ActionPerformed

    private void LB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LB3ActionPerformed
        p2.paro();
        respuesta2 = true;
        comprobarResultado();
    }//GEN-LAST:event_LB3ActionPerformed

    private void LB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LB4ActionPerformed
        p3.paro();
        respuesta3 = true;
        comprobarResultado();
    }//GEN-LAST:event_LB4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tragamonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tragamonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tragamonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tragamonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tragamonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB1;
    private javax.swing.JButton LB2;
    private javax.swing.JButton LB3;
    private javax.swing.JButton LB4;
    private javax.swing.JLabel lb1Persona1;
    private javax.swing.JLabel lb2Persona2;
    private javax.swing.JLabel lb3Persona3;
    private javax.swing.JButton lb5;
    private javax.swing.JComboBox<String> lb6;
    // End of variables declaration//GEN-END:variables

     private void comprobarResultado() {
         if (respuesta1 && respuesta2 && respuesta3){
             try {
                 Thread.sleep(100);
             } catch (InterruptedException ex) {
                 Logger.getLogger(Tragamonedas.class.getName()).log(Level.SEVERE, null, ex);
             }
             lb5.setEnabled(true);
             if (lb1Persona1.getIcon().toString().equals(lb2Persona2.getIcon().toString()) && lb1Persona1.getIcon().toString().equals(lb3Persona3.getIcon().toString())) {
                 JOptionPane.showMessageDialog(null, "Felicidades, has ganado!");
             } else {
                 JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
             }
         }
     }
}

